### ISSUE TITLE
What about a subject instead of creating Observable

### ISSUE THREAD

**Issue by blackpr** [thelgevold/rxjs-socket.io#2]
Hello,
this is not an issue just a question.

In the chat.service.ts you have getMessage method and you are creating and returning a new Observable.

I am wondering. What if this method is implemented with Subject. Is that wrong?

example:

``` typescript
  getMessagesSubject() {
    this.socket = io(this.url);
    let subject = new Subject();
    this.socket.on('message', (data) => {
        subject.next(data);
    });
    return subject;
  }
```

ps: Awesome tutorial.

**Comment by thelgevold** [comment]
Yes, you can do it that way as well. In my case I wanted to demo how you can create your own observables. 

If you return a subject the caller will have access to the next method on the subject and will be able to next out new messages. With a simple observable the "next" part is private to the getMessage method.

**Comment by blackpr** [comment]
It makes sense.
Thank you
