### ISSUE TITLE
Consider upgrading to latest tools

### ISSUE THREAD

**Issue by kylelib** [thelgevold/rxjs-socket.io#8]
Please consider upgrading the code to use the latest tools. I'm trying to kick the tires on Socket.io and thought your sample might help. Sadly it did not run given the ReadMe instructions. I am getting exceptions from `ng-serve` suggesting issues with angular-cli and webpack.

**Comment by thelgevold** [comment]
Hi.
This PR https://github.com/thelgevold/rxjs-socket.io/pull/9 upgraded to the current versions
